print('Project title: Canteen Order System')
print("Group name: Squad Zero")
print("") 
print("======================================")
print("    COM 103 PROJECT -- TASK TYPES     ")  
print("======================================")
print(" 1. Program Logic / Coding       [6h] ")
print(" 2. UI / Output Formatting       [3h] ")
print(" 3. Testing & Debugging          [2h] ")
print(" 4. Documentatioin / README      [2H] ")
print(" 5. Presentation Slides          [2H] ")
print("======================================")